#!/usr/bin/env node
// scripts/genSearchIndex.mjs
//
// Builds public/search-index.json: a compact array of every file entry found
// in folders/*.json, so the curriculum page can offer a site-wide filename
// search without a server. Run automatically before `next build` via the
// "prebuild" npm script (folders/ is regenerated by scripts/genIndex.mjs in
// CI before this runs).
//
// Output entry shape: { n: <fileName>, i: <fileId>, r: <系名 › parent folder route> }
//
// 沒有 folders/ 就寫一份空索引而不是中斷：CI 那邊 genIndex 自己失敗就會讓
// workflow 紅燈，這裡再擋一次只會讓「還沒設 API key」的首次部署無法上線。

import fs from 'fs';
import path from 'path';

const ROOT_DIR = process.cwd();
const FOLDERS_DIR = path.join(ROOT_DIR, 'folders');
const OUTPUT_PATH = path.join(ROOT_DIR, 'public', 'search-index.json');

function writeEmpty(reason) {
    console.warn(`Warning: ${reason} Writing an empty search index.`);
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, '[]', 'utf8');
    process.exit(0);
}

// 系代碼 → 系名，用來在搜尋結果的路徑前標出系所。
function loadDeptNames() {
    for (const f of ['depts.resolved.json', 'depts.json']) {
        const p = path.join(ROOT_DIR, f);
        if (!fs.existsSync(p)) continue;
        try {
            const list = JSON.parse(fs.readFileSync(p, 'utf8'));
            return Object.fromEntries(list.map((d) => [d.code, d.name]));
        } catch (err) {
            console.warn(`Warning: failed to parse ${f}: ${err.message}`);
        }
    }
    return {};
}

const deptNames = loadDeptNames();

if (!fs.existsSync(FOLDERS_DIR) || !fs.statSync(FOLDERS_DIR).isDirectory()) {
    writeEmpty(`${FOLDERS_DIR} does not exist.`);
}

const jsonFiles = fs.readdirSync(FOLDERS_DIR).filter((f) => f.endsWith('.json'));

if (jsonFiles.length === 0) {
    writeEmpty(`${FOLDERS_DIR} is empty (no .json files found).`);
}

const index = [];

for (const fileName of jsonFiles) {
    const fullPath = path.join(FOLDERS_DIR, fileName);
    // 檔名格式 <系code>__<課程碼>.json
    const deptCode = fileName.split('__')[0];
    const deptLabel = deptNames[deptCode] || deptCode;
    let data;
    try {
        data = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    } catch (err) {
        console.error(`Error: failed to parse ${fullPath}: ${err.message}`);
        process.exit(1);
    }

    for (const folderId of Object.keys(data)) {
        const folder = data[folderId];
        const route = folder && folder.route;
        const files = (folder && folder.file) || [];
        for (const file of files) {
            index.push({
                n: file.name,
                i: file.url,
                r: `${deptLabel} › ${route}`,
                d: deptCode,
            });
        }
    }
}

if (index.length === 0) {
    writeEmpty('no file entries found across folders/*.json.');
}

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, JSON.stringify(index), 'utf8');

console.log(`Wrote ${index.length} file entries to ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
