#!/usr/bin/env node
// scripts/genSearchIndex.mjs
//
// Builds public/search-index.json: a compact array of every course and file
// entry, so the navbar can offer a site-wide search without a server.
// Run automatically before `next build` via the
// "prebuild" npm script (folders/ is regenerated by scripts/genIndex.mjs in
// CI before this runs).
//
// Course: { k: 'course', n: <courseName>, r: <系名 › 課程>, u: <coursePath> }
// File:   { k: 'file', n: <fileName>, i: <fileId>, r: <系名 › parent route> }
//
// 沒有 folders/ 就寫一份空索引而不是中斷：CI 那邊 genIndex 自己失敗就會讓
// workflow 紅燈，這裡再擋一次只會讓「還沒設 API key」的首次部署無法上線。

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { displayName, displayRoute } from '../lib/displayName.mjs';

const ROOT_DIR = process.cwd();
const FOLDERS_DIR = path.join(ROOT_DIR, 'folders');
const CURRICULUMS_DIR = path.join(ROOT_DIR, 'curriculums');
const OUTPUT_PATH = path.join(ROOT_DIR, 'public', 'search-index.json');

function writeEmpty(reason) {
    console.warn(`Warning: ${reason} Writing an empty search index.`);
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, '[]', 'utf8');
    process.exit(0);
}

// 系代碼 → 系名，用來在搜尋結果的路徑前標出系所。
function loadDeptNames() {
    for (const f of ['depts.resolved.json', 'depts.json']) {
        const p = path.join(ROOT_DIR, f);
        if (!fs.existsSync(p)) continue;
        try {
            const list = JSON.parse(fs.readFileSync(p, 'utf8'));
            return Object.fromEntries(list.map((d) => [d.code, d.name]));
        } catch (err) {
            console.warn(`Warning: failed to parse ${f}: ${err.message}`);
        }
    }
    return {};
}

const deptNames = loadDeptNames();

if (!fs.existsSync(FOLDERS_DIR) || !fs.statSync(FOLDERS_DIR).isDirectory()) {
    writeEmpty(`${FOLDERS_DIR} does not exist.`);
}

const jsonFiles = fs.readdirSync(FOLDERS_DIR).filter((f) => f.endsWith('.json'));

if (jsonFiles.length === 0) {
    writeEmpty(`${FOLDERS_DIR} is empty (no .json files found).`);
}

const index = [];

// 課程排在檔案前面，讓同時命中時「前往課程頁」優先被看到。
if (fs.existsSync(CURRICULUMS_DIR)) {
    const curriculumFiles = fs.readdirSync(CURRICULUMS_DIR).filter((f) => f.endsWith('.md'));
    for (const curriculumFile of curriculumFiles) {
        const id = curriculumFile.replace(/\.md$/, '');
        const fullPath = path.join(CURRICULUMS_DIR, curriculumFile);
        try {
            const { data } = matter(fs.readFileSync(fullPath, 'utf8'));
            if (!data.title || !data.fid) continue;
            const deptCode = data.dept || id.split('__')[0];
            const deptLabel = deptNames[deptCode] || data.deptName || deptCode;
            index.push({
                k: 'course',
                n: displayName(data.title, deptCode),
                r: `${deptLabel} › 課程`,
                u: `/folder/${encodeURIComponent(id)}/${encodeURIComponent(String(data.fid))}`,
                d: deptCode,
            });
        } catch (err) {
            console.error(`Error: failed to parse ${fullPath}: ${err.message}`);
            process.exit(1);
        }
    }
}

for (const fileName of jsonFiles) {
    const fullPath = path.join(FOLDERS_DIR, fileName);
    // 檔名格式 <系code>__<課程碼>.json
    const deptCode = fileName.split('__')[0];
    const deptLabel = deptNames[deptCode] || deptCode;
    let data;
    try {
        data = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
    } catch (err) {
        console.error(`Error: failed to parse ${fullPath}: ${err.message}`);
        process.exit(1);
    }

    for (const folderId of Object.keys(data)) {
        const folder = data[folderId];
        const route = folder && folder.route;
        const files = (folder && folder.file) || [];
        for (const file of files) {
            index.push({
                k: 'file',
                n: file.name,
                i: file.url,
                r: `${deptLabel} › ${displayRoute(route, deptCode)}`,
                d: deptCode,
            });
        }
    }
}

if (index.length === 0) {
    writeEmpty('no file entries found across folders/*.json.');
}

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, JSON.stringify(index), 'utf8');

const courseCount = index.filter((entry) => entry.k === 'course').length;
console.log(`Wrote ${courseCount} course and ${index.length - courseCount} file entries to ${path.relative(ROOT_DIR, OUTPUT_PATH)}`);
